name: WordPress Coding Standards (WPCS)

on:
  push:
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'

jobs:
  lint:
    name: PHP CodeSniffer Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run PHP CodeSniffer (10up)
        uses: 10up/wpcs-action@stable
        with:
          # Automatically uses WordPress coding standards
          standard: WordPress
          # Disables warnings (-n) to ensure your action doesn't fail purely over docblock syntax 
          extra_args: '-n --extensions=php --ignore=*/plugin-update-checker/*,*/vendor/*,*/node_modules/* .'
