name: WordPress Coding Standards (WPCS)

on:
  push:
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'

jobs:
  lint:
    name: PHP CodeSniffer Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer

      - name: Install WPCS via Composer
        run: |
          # 1. Allow the auto-installer to map WPCS into PHPCS
          composer global config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          
          # 2. Install PHP_CodeSniffer, the WordPress Standard, and the Auto-installer
          composer global require squizlabs/php_codesniffer wp-coding-standards/wpcs dealerdirect/phpcodesniffer-composer-installer

      - name: Run PHP CodeSniffer
        run: |
          phpcs --standard=WordPress -n --extensions=php --ignore=*/plugin-update-checker/*,*/vendor/*,*/node_modules/* .
