name: Build and Package Plugin Release

# 1. When should this script run?
# We only want it to run when you publish a new "Release" on GitHub.
on:
  release:
    types: [published]

# 2. What jobs should it perform?
jobs:
  build:
    name: Build & Attach Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to upload files to GitHub Releases
      
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Create Build Directory
      run: |
        mkdir optiMessage
        # Copy everything except development metadata
        rsync -av --progress . optiMessage/ --exclude optiMessage --exclude .git --exclude .github --exclude .DS_Store
      
    - name: Generate Zip File
      run: zip -r optiMessage.zip optiMessage

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: optiMessage.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
